FRONTENDSCHOOL8/pocket-karly

vite.config.js

- 환경 설정 테스트
<br />
<br />
<br />
<br />
<br />

[Test] vite.config.js 파일에 header 추가

---

vite.config.js

- 환경 설정 테스트
<br />
<br />
<br />
<br />
<br />

[Test] vite.config.js 파일에 footer 삭제

---

tailwind.config.js

- width의 innerWrapper : 1050px 설정
<br />
<br />
tailwind config 파일 변경
<br />
width에 관련하여 innerWrapper:1050px 추가
<br />
<br />

[Chore] tailwind config 추가

---

main.js
src/js/popup.js
src/pages/components/popup.html
vite.config.js

<br />
<br />
- popup 기능 추가
<br />
- 팝업창 클릭 시 이동하는 페이지는 메인페이지 완성 후 연결 필요
- 오늘 하루 안 보기 버튼 클릭 시 하루 동안 팝업창이 활성화되지 않음
- 닫기 버튼 클릭 시 페이지가 리로드되면 팝업창이 다시 활성화
- 팝업 기능은 popup.js에서 export하여 main.js에서 import
<br />
<br />
resolves #32

[Feat] popup 기능 추가

---

src/pages/components/footer.html
src/styles/footer.css
src/styles/tailwind.css

<br />
<br />
<br />
<br />
<br />
resolves #11
resolves #22

[Feat] footer 추가

---

src/pages/components/footer.html
src/styles/button.css
src/styles/footer.css
src/styles/tailwind.css

<br />
<br />
버튼 클래스 추가
<br />
button.css 파일 추가
footer 클래스명 변경 (코드 변경X)
footer.css 삭제
<br />
<br />

[Design] 버튼 공통 스타일 button.css 추가

---

src/js/addCart.js
src/js/popup.js
src/pages/components/addCart.html
src/pages/components/popup.html
vite.config.js

<br />
<br />
장바구니 버튼 클릭 시 나타나는 addCart 모달창 제작
<br />
- 할인 적용 유무에 따른 테스트 상품DB 연결
- 수량 버튼에 따른 총 구매 가격과 적립금 변경(0.05%) 적용
- 로그인페이지 제작 후 로컬스토리지/DB 작업 필요
- 메인페이지/목록페이지 제작 후 로컬스토리지/DB 작업 필요
<br />
|할인 미적용 상품|할인 적용 상품|수량 변경|
|------|------|---|
|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/7ff18f6a-fd49-4055-ab96-82438275714c)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/4a23f744-c224-4133-a388-7de8b0bceb2c)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/7db9667a-d28b-4755-997e-eb88e3b56775)|
<br />
resloves #35, #47 #51

[Feature] add_cart 모달창 제작

---

src/pages/components/header.html
src/pages/components/header.js

<br />
<br />
헤더 스타일링 변경, tailwind import 변경
<br />
- 헤더 최상단 고객센터 호버시 나타나는 메뉴에 z-index 값 부여
- tailwind import js파일로 수정
<br />
<br />

[Design] 헤더 스타일링 변경, tailwind import 변경

---

public/icons/_sprite.svg
src/pages/detail/detail2.js
src/pages/detail/index2.html
src/pages/register/index.html
src/pages/register/register.css
src/pages/register/register.js
src/styles/tailwind.css

<br />
<br />
- 체크박스 수정 및 밸리데이션 추가
- 상세페이지 하단 마크업 및 디자인 시작
<br />
- 체크박스 전체동의 부분, 개별 항목 체크 후 클릭 시 개별항목에 적용되지 않는 이슈
- 체크박스 아이콘 클릭 시 체크가 되지 않는 이슈
<br />
<br />
resolves #16 #12 #3 #4 #7 #9

[Feat] 회원가입 페이지 

---

src/pages/register/index.html
src/pages/register/register.js

- 다음 주소 기능 추가
- 전체동의 이슈 해결
- 회원정보 DB 항목 추가
- 유효성 검사 마무리
<br />
<br />
<br />
<br />
<br />

[Feat] 회원가입 마무리

---

src/pages/login/index.html
src/pages/login/login.js
tailwind.config.js

- db에 유저아이디가 있을 경우 로그인성공
- 없을 경우 모달창 구현 필요
- 로그인됐을 때 로컬스토리지에 저장
<br />
<br />
<br />
<br />
<br />

[Feat] 로그인페이지 구현

---

src/pages/components/header.html

<br />
<br />
헤더에 box-shadow 추가
<br />
<br />
<br />

[Design] 헤더에 box-shadow 추가

---

src/pages/components/addressApi.js
src/pages/register/index.html
src/pages/register/register.js

<br />
<br />
- 각 밸리데이션에 따른 버튼 활성화 구현
- 필수입력상태 기능 추가 및 그에 따른 가입확인 버튼 활성화
- 주소 value에 따른 UI 변경 기능 추가
<br />
<br />
<br />

[Feat] 회원가입 페이지 완성

---

src/pages/register/index.html
src/pages/register/register.css

<br />
<br />
-  radio, check 버튼 클릭 시 클릭이 안되고, label에 의해서 만 작동하는 에러를 수정
- bg로 준 svg 위로 동일한 사이즈의 Input 배치 후 appearance none 처리
- 이후 포커스도 잘 작동해서 접근성 측면에서도 아주 좋은 결과를 얻음
<br />
<br />
<br />

[Design] input radio, check 수정

---

src/pages/login/index.html
src/pages/login/login.js

- 로그인 인증 후 메인페이지로 이동
- 로그인페이지 마크업 수정
<br />
<br />
<br />
<br />
<br />

[Feat] 로그인페이지

---

src/pages/components/js/include.js

<br />
<br />
헤더 최상단 회원 이름 호버 했을 경우 '탈퇴하기' 기능 사용할 수 있도록 함
<br />
<br />
<br />
#112

[Feat] 회원 탈퇴 기능 추가

---

vite.config.js

<br />
<br />
vite config 파일에 login.html 경로 추가
<br />
<br />
<br />

[Chore] 로그인 빌드추가

---

public/icons/_sprite.svg
src/assets/svg/_sprite.svg
src/assets/svg/pageArrow-left.svg
src/assets/svg/pageArrow-right.svg
src/pages/detail/detail2.css
src/pages/detail/index2.html

<br />
<br />
- svg추가  : 상세페이지 하단 상품리뷰 및 상품문의 pagenation을 위한 svg 추가 및 sprite 수정
- 상세페이지 하단 상품리뷰 및 상품문의 마크업 및 디자인
<br />
<br />
<br />

[Design] 상품리뷰 및 상품문의 마크업 및 디자인

---

src/pages/cart/cart.js
src/pages/cart/index.html
src/styles/tailwind.css
vite.config.js

<br />
<br />
- 장바구니 레이아웃 완성
- 장바구니 기능 진행 중
<br />
- 마크업 문법 검사 완료
- 레이아웃 완성
- sticky 적용
- accordion 적용 (상품 목록 토글)
- DB 연결
- 포장 타입 분류에 따른 장바구니 상품 목록 정렬
- X버튼 클릭 시 장바구니 화면 및 DB에서 상품 삭제
- 상품 개별 동작: 수량 선택 및 수량에 따른 금액 출력
- 각 상품의 수량은 1 미만이 될 수 없음
- 전체 금액 합산: (상품 금액, 상품 할인 금액, 결제 예정금액) 출력
- 총 주문 금액이 40000원 미만일 경우 배송비 3000원 추가, 이상일 경우 무료
<br />
|예시1|예시2|
|---|---|
|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/fa8e2134-2b7d-4489-9914-53f76f2eb88e)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/3e4b55e4-70a3-4756-a603-c98c9072b2cb)|
<br />
resolves #33, #34, #35, #36, #38

[Feat] 장바구니 페이지 레이아웃 완성 및 기능 추가

---

index.html
main.js
src/pages/cart/cart.js
src/pages/cart/index.html
src/pages/components/footer.html
src/pages/components/js/include.js
src/pages/components/sidebar.html
src/pages/detail/detail.js
src/pages/detail/index.html
src/pages/login/index.html
src/pages/login/login.js
src/pages/productList/index.html
src/pages/productList/productList.js
src/pages/register/index.html
src/pages/register/register.js

<br />
<br />
각 페이지에 header, footer, sidebar include
<br />
- 각 페이지에 header, footer, sidebar include
- 로그인 페이지 margin bottom값 추가
<br />
<br />

[Design] 각 페이지에 header, footer, sidebar include

---

src/pages/cart/index.html
src/pages/components/addCart.html

<br />
<br />
- 체크박스 버튼 기능 작업 중
<br />
- 전체선택 클릭 시 모든 checkbox 선택 기능 추가
- 전체선택 2개 버튼 연결
- checkbox 선택 상태 변수 관리 (진행 중)
<br />
<br />
resolves #36

[Feat] 장바구니 페이지 체크박스 버튼 기능 추가

---

main.js

<br />
<br />
메인페이지 무한루프 버그 수정
<br />
- 랜덤으로 데이터 뽑아오는 경우 무한 루프 버그 해결
<br />
<br />

[BugFix] 메인페이지 무한루프 버그 수정

---

src/pages/cart/cart.js
src/pages/cart/index.html

<br />
<br />
<br />
- 배송지 주소 API 추가
- 상태변수 관리 추가 (checkState 함수 추가)
- checkbox id 수정, data 속성 추가
- 전체선택 checkbox 연결
- 전체 상품 개수 추가
<br />
<br />

[Feat] 장바구니 기능 추가

---

src/pages/cart/cart.js

<br />
<br />
- 개별 상품 선택, 전체 선택에 따라 상품의 체크 유무를 productState에서 관리
<br />
<br />
<br />
resolves #36

[BugFix] 장바구니 상태변수 관리 수정

---

main.js
src/pages/productList/productList.js

- 상품 목록에서 할인율 있을 경우만 원래 가격 보여주도록 수정
<br />
<br />
상품 목록 가격 출력 오류 수정
<br />
- 상품 목록에서 할인율 있을 경우만 원래 가격 보여주도록 수정
<br />
<br />

[BugFix] 상품 목록 가격 출력 오류 수정

---

index.html
src/pages/cart/cart.js
src/pages/cart/index.html
src/pages/components/addCart.html
src/pages/productList/index.html
src/styles/button.css

<br />
<br />
- 장바구니의 상품 유무에 따라 UI 변경
- 회원 여부에 따라 UI 변경
- addCart 모달창 레이아웃 무너지는 부분 수정 (각 페이지에 수정사항 반영 완료)
<br />
<br />
<br />
resolves #39

[Feat] 회원 여부/상품 유무에 따른 장바구니 UI 및 기능 분리

---

src/pages/productList/index.html
src/pages/productList/productList.js

<br />
<br />
- 상품 상세페이지 왼쪽 필터에서 카테고리, 브랜드 옆에 카운트 추가
<br />
<br />
<br />

[Feat] 상품 상세페이지 카테고리, 브랜드 필터 옆에 카운트 추가

---

src/pages/login/login.js

<br />
<br />
기존에 로그인 시 메인으로 이동하는 것에서 이전 페이지로 이동하는 것으로 변경
<br />
<br />
<br />

[Feat]로그인 시 이전 페이지로 이동

---

src/pages/detail/detail.js

<br />
<br />
- 최근본상품 오류 해결
<br />
- 최근본상품 처음 등록 시 상품 상세페이지에서 swiper에 제품 안보이는 문제 해결
<br />
<br />

[BugFix] 최근본상품 오류 해결

---

src/pages/cart/cart.js
src/pages/components/js/addressApi.js

<br />
<br />
배송지 변경 기능 추가
<br />
<br />
|주소 변경 전|주소 선택|상세주소 입력 중|주소 변경 완료|
|------|---|---|---|
|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/180dd64b-d86c-4685-8991-849d9fb6052e)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/c5860f9a-c023-4864-9595-0fcdd7ca3b14)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/4d842752-d178-46f1-9b9d-d9504d311a7e)|![image](https://github.com/FRONTENDSCHOOL8/pocket-karly/assets/148831765/3b5a25f9-53aa-4ab5-813d-d30270ec159d)|
<br />
resolves #37

[Feat] 장바구니 페이지 배송지 변경 기능 추가

---

index.html
main.js

- 기존에 HTML에서 이미지 불러오던 형식에서 DB에서 데이터 불러와 그려주는 방식으로 변경
<br />
<br />
<br />
- 기존에 HTML에서 이미지 불러오던 형식에서 DB에서 데이터 불러와 그려주는 방식으로 변경
<br />
<br />

[Modify] 메인페이지 배너 DB데이터로 출력

---

index.html
main.js

<br />
<br />
메인페이지팝업 기능 추가
<br />
- popup.html 코드 메인페이지 index.html에 추가
- main.js에 cart.js import
<br />
<br />
resolves #32

[Feat] 메인페이지 팝업 기능 추가

---

src/api/defaultAuthData.js
src/pages/components/js/addressApi.js
src/pages/detail/detail2.js
src/pages/detail/index.html
src/pages/register/index.html
src/pages/register/register.js

<br />
<br />
- 로그인사용자, 상품 페이지와 연동
- 비밀글일 경우 본인 글만 보이도록
- 주소api.js 수정
<br />
<br />
<br />

[Feat] 상세페이지 하단 기능 구현

---

src/pages/detail/detail.js
src/pages/detail/index.html

- 로그인시 비회원시 적립금 분리
<br />
<br />
<br />
<br />
<br />

[Feat] 상세페이지

---

src/pages/cart/cart.js
src/pages/cart/index.html

<br />
<br />
- 상품 삭제 기능 조건처리(회원/비회원)
- 비회원 상품삭제 오류 수정
- 회원 적립금 수정
<br />
- 상품 삭제 기능 회원/비회원 분리
- 비회원의 경우 상품 삭제 시 로컬스토리지 cart 업데이트
- 결제예정금액에 따른 회원 예상 적립금출력
<br />
<br />
resolves #36 #39 #47

[BugFix] 장바구니페이지 비회원 상품삭제 기능 수정

---

src/pages/components/js/modals.js
src/pages/components/modal.html

<br />
<br />
기본 확인 모달 컴포넌트 제작
<br />
- 2가지 타입으로 제작: alert, confirm (modal.html 참고)
- 사용법 modals.js 참고
<br />
<br />

[Feat] 기본 확인 모달 컴포넌트 제작

---

src/lib/utils/getPbImageURL.js
src/pages/detail/detail.js
src/pages/detail/index.html

<br />
<br />
<br />
- 상세정보 페이지의 이미지 alt를 데이터베이스에서 가져오도록 함
<br />
<br />
#156

[Feat] 상세정보 페이지 이미지 alt 가져오기

---

src/pages/cart/index.html
src/pages/detail/detail.js
src/pages/productList/index.html
src/pages/productList/productList.js

<br />
<br />
<br />
- 페이지 당 상품 9개 보이도록 수정
- 페이지별 title 변경
<br />
<br />

[Modify] 상품 출력 개수 수정, 페이지 타이틀 변경

---

src/pages/detail/detail2.js
src/pages/detail/index.html

<br />
<br />
[bug] sort기능 버그
- sort를 누르면 원하는 대로 기존 글이 지워지지 않고 새로 정렬된 글이 추가 됌
- 리뷰 sort 기능에서 함수안에 같은 함수를 불러와서 생기는 오류로 보임
<br />
<br />
<br />

[Bug] sort 기능 버그발생

---

src/pages/detail/detail2.js
src/pages/detail/index.html

<br />
<br />
- 범쌤의 지도 : 굳이 동적으로 만든 node를 잡아 지우려 하지말고, 동적으로 넣는 템플릿은 div로 감싸 놓는 버릇을 들여라 (그 div의 textContent를 지우면 됨)
- 지우님의 솔루션 :
함수 선언과 getNodes선언 위치를 수정
<br />
<br />
<br />

[bugFix] 상세페이지 sort 버그 수정

---

README.md

<br />
<br />
<br />
<br />
<br />

[Docs] README.md 작성

---

main.js
src/pages/detail/detail.js
src/pages/detail/index.html

- 슬라이드가 없을 시 버튼 제거
- 좋아요버튼 클릭 시 변경
- 비회원일 경우 로그인 창으로 이동
<br />
<br />
- 넘어갈 수 있는 슬라이드가 없을 경우 버튼 제거
- 좋아요버튼 클릭 시 변경(회원일 경우)
- 비회원일 경우 로그인 창으로 이동
<br />
<br />
<br />

[Feat] 메인 스와이퍼, 상세 페이지

---

src/pages/detail/detail.js

<br />
<br />
<br />
- 비회원이 장바구니 담기 이용시 local storage에 상품 저장
- 회원이 장바구니 담기 이용시 DB에 상품 저장
<br />
<br />

[Feat] 상세페이지 장바구니 담기 기능 추가

---

main.js
src/pages/detail/detail.js
src/pages/detail/index.html

- 메인페이지 전체보기 이동
- 상세페이지 마크업 변경
<br />
<br />
상세페이지 줄처리
스와이퍼 전체보기 상품목록 페이지로 이동
<br />
<br />
<br />

[Feat] 메인, 상세페이지

---

src/pages/cart/cart.js
src/pages/detail/detail.js
src/pages/detail/detail2.js

<br />
<br />
<br />
- console.log 삭제
<br />
<br />

[Modify] console.log 삭제

---

src/pages/detail/index.html

<br />
<br />
<br />
- id 추가
<br />
<br />

[Modify] id 추가

---

src/pages/detail/detail2.js
src/pages/detail/index.html

- 도움돼요 버튼으로 인한 정렬버튼 클릭 이벤트 간섭 해결
<br />
<br />
<br />
<br />
<br />

[BugFix] 리뷰 선택버튼 버그

---

src/pages/cart/cart.js

<br />
<br />
장바구니페이지 처음 접속 시 마이너스 버튼 클릭이 되지 않는 문제 해결
<br />
<br />
<br />

[Bugfix] 장바구니페이지 수량변경 버튼 오류 수정

---

src/pages/components/js/include.js
src/pages/productList/productList.js

<br />
<br />
<br />
- 낮은 가격순, 높은 가격순 사용할 경우 기준을 '원가'가 아닌 원가에 discount가 반영된 가격을 기준으로 정렬해줘야함
<br />
<br />

[BugFix] 상품 목록 페이지 정렬 수정

---

src/pages/detail/detail.js
src/pages/detail/index.html

- 스티키 처리
- 알레르기 구분
<br />
<br />
<br />
<br />
<br />

[Modify] 상세페이지

---

src/pages/login/index.html
src/pages/login/login.js
src/pages/register/index.html
src/pages/register/register.js

<br />
<br />
<br />
<br />
<br />

[Modify] 회원가입/로그인 alert 커스텀

---

src/pages/register/index.html

<br />
<br />
회원가입페이지 alert 커스텀을 위한 html 추가
<br />
- 누락된 dialog 추가
- 사용하지 않는 script 삭제
<br />
<br />

[Modify] 회원가입페이지 모달 추가

---

src/pages/detail/detail.js
src/pages/detail/detail2.js
src/pages/detail/index.html
src/pages/register/register.js

<br />
<br />
<br />
<br />
<br />

[Modify] 상품 상세페이지 alert 커스텀

---

src/pages/detail/detail.js
src/pages/detail/index.html

<br />
<br />
탭 메뉴 클릭 시 주소의 hash값이 변하는 오류 수정
<br />
<br />
<br />

[BugFix] 상품 상세페이지 탭 메뉴 스크롤 이동 오류 수정

---

src/pages/components/js/addCart.js

- 장바구니 담기 이용시 뜨던 alert 삭제(화면 상단에 말풍선으로 대체)
<br />
<br />
<br />
- 장바구니 담기 이용시 뜨던 alert 삭제(화면 상단에 말풍선으로 대체)
<br />
<br />

[Modify] 장바구니 담기 이용시 뜨던 alert 삭제
